repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      types: [python]
      args: [--config, ./pyproject.toml]
      language_version: python3.8
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        types: [ python ]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: migrations
        args: [--config, ./.flake8]
        additional_dependencies:
          - flake8-bugbear
          - flake8-variables-names
          - flake8-simplify
          - flake8-pie
          - flake8-commas
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-print
          - flake8-quotes
          - dlint