version: '3'
services:

  db:
    image: postgres:14.3
    container_name: postgres_db
    environment:
      POSTGRES_DB: $PG_DB
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    env_file:
      - .env
    restart: always

  auth-test:
    build:
      context: .
      args:
        PROJECT_ENV: test
    env_file:
      - .env
    entrypoint: ["sh", "src/test.sh"]
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"

  redis:
    image: redis:7.0.4-alpine
    expose:
      - 6379
    restart: always