"""empty message

Revision ID: fb80c9eb93fa
Revises: 7b480ce3b6af
Create Date: 2022-09-27 14:01:44.633960

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb80c9eb93fa'
down_revision = '7b480ce3b6af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'social_account',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('create_at', sa.TIMESTAMP(), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('social_id', sa.Text(), nullable=False),
        sa.Column('social_name', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['auth.users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('social_id', 'social_name', name='social_pk'),
        schema='auth',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_account', schema='auth')
    # ### end Alembic commands ###
